// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaythosAerospace.Models.Repositories;

namespace RaythosAerospace.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231129171401_added-relationships")]
    partial class addedrelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RaythosAerospace.Models.Repositories.AirCraftRepository.AirCraftModel", b =>
                {
                    b.Property<string>("AircraftId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AircraftType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("FuelCapacity")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("ManfacturedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAllowedEngines")
                        .HasColumnType("int");

                    b.Property<int>("MaxSeatesAllowed")
                        .HasColumnType("int");

                    b.Property<int>("MaxWingSpan")
                        .HasColumnType("int");

                    b.Property<double>("MaximumRange")
                        .HasColumnType("float");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("AircraftId");

                    b.HasIndex("EngineId");

                    b.HasIndex("SeatID");

                    b.ToTable("AirCrafts");
                });

            modelBuilder.Entity("RaythosAerospace.Models.Repositories.AirCraftRepository.EngineModel", b =>
                {
                    b.Property<string>("EngineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitCount")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("EngineId");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            EngineId = "E0000",
                            EngineType = "Turbojet",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0001",
                            EngineType = "Turbofan",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0002",
                            EngineType = "Turboprop",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0003",
                            EngineType = "Turboshaft",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0004",
                            EngineType = "Piston",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0005",
                            EngineType = "Ramjet",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0006",
                            EngineType = "HybridElectric",
                            UnitCount = 6,
                            UnitPrice = 1000
                        },
                        new
                        {
                            EngineId = "E0007",
                            EngineType = "Other",
                            UnitCount = 6,
                            UnitPrice = 1000
                        });
                });

            modelBuilder.Entity("RaythosAerospace.Models.Repositories.AirCraftRepository.SeatModel", b =>
                {
                    b.Property<string>("SeatID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("SeatID");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatID = "S0000",
                            SeatCount = 10,
                            SeatType = "Economy",
                            UnitPrice = 200
                        },
                        new
                        {
                            SeatID = "S0001",
                            SeatCount = 10,
                            SeatType = "PremiumEconomy",
                            UnitPrice = 200
                        },
                        new
                        {
                            SeatID = "S0002",
                            SeatCount = 10,
                            SeatType = "Business",
                            UnitPrice = 200
                        },
                        new
                        {
                            SeatID = "S0003",
                            SeatCount = 10,
                            SeatType = "FirstClass",
                            UnitPrice = 200
                        },
                        new
                        {
                            SeatID = "S0004",
                            SeatCount = 10,
                            SeatType = "Other",
                            UnitPrice = 200
                        });
                });

            modelBuilder.Entity("RaythosAerospace.Models.Repositories.AirCraftRepository.AirCraftModel", b =>
                {
                    b.HasOne("RaythosAerospace.Models.Repositories.AirCraftRepository.EngineModel", "EngineType")
                        .WithMany("AirCraftModels")
                        .HasForeignKey("EngineId");

                    b.HasOne("RaythosAerospace.Models.Repositories.AirCraftRepository.SeatModel", "Seat")
                        .WithMany("AirCraftModels")
                        .HasForeignKey("SeatID");

                    b.Navigation("EngineType");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("RaythosAerospace.Models.Repositories.AirCraftRepository.EngineModel", b =>
                {
                    b.Navigation("AirCraftModels");
                });

            modelBuilder.Entity("RaythosAerospace.Models.Repositories.AirCraftRepository.SeatModel", b =>
                {
                    b.Navigation("AirCraftModels");
                });
#pragma warning restore 612, 618
        }
    }
}
